"""Full-year demo journal data for Pocket Confidant.

365 entries spanning July 2025 – June 2026. Each entry references real people,
projects, rituals, preferences, and themes so the memory atoms and recall
features light up immediately in demo mode.

This file is imported by engine/store.py — do not load it at runtime in the
Gradio app; it is only consumed by seed_demo().
"""

# (day, text) tuples — one per day.
# People: Mom, Dad, Sarah, Daniel, Max, Lena, Raj, Katie, Uncle Pete,
#         Grandma, Tom (boss), Yuki, Chris (barista), Maria (yoga), Jake
# Projects: Pocket Confidant, community garden, kitchen renovation,
#           photography portfolio, blog, volunteer tutoring
# Rituals: morning coffee, evening walk, Sunday cooking, Thursday chess,
#          Friday movie night, vitamins, journaling, yoga, reading before bed
# Preferences: quiet mornings, dark chocolate, camping, rain sounds,
#              alone time, cooking, old bookstores, walking
# Themes: burnout, creativity, family, boundaries, growth, seasonal,
#         friendship, loneliness, ambition, self-care

DEMO_ENTRIES: list[tuple[str, str]] = [
    # ================================================================
    # JULY 2025 — new apartment, fresh start
    # ================================================================
    ("2025-07-01", "Moved into the new apartment today. Boxes everywhere but the light through the kitchen window is good."),
    ("2025-07-02", "Unpacking. Found the old camping stove under Dad's things. Made coffee on it. Felt like a small victory."),
    ("2025-07-03", "Called Mom. She asked if the apartment has a good closet. It does. She'll be relieved."),
    ("2025-07-04", "Independence Day. The neighbors are setting off fireworks. I watched from the porch with a beer. Quiet celebration."),
    ("2025-07-05", "Walked to the corner store. Chris at the register remembered my name already. Nice guy."),
    ("2025-07-06", "Sunday cooking. Made a big batch of pasta sauce. The kitchen smells like home now."),
    ("2025-07-07", "First morning coffee on the porch. The neighborhood is quieter than the old place. I needed quiet."),
    ("2025-07-08", "Work was productive. Tom seems pleased with the new setup. I'm settling into the commute."),
    ("2025-07-09", "Sarah came over to help unpack. We ordered Thai and sat on the floor because I still don't have a dining table."),
    ("2025-07-10", "Yoga with Maria for the first time. She moves slowly and deliberately. I liked the pace."),
    ("2025-07-11", "Started thinking about the community garden plot. Yuki mentioned there's one available on Elm Street."),
    ("2025-07-12", "Friday movie night. Watched an old film on my laptop. The screen is small but the stories are big."),
    ("2025-07-13", "Sunday cooking. Made a big pot of soup. The kitchen is small but everything works."),
    ("2025-07-14", "Walked past the community garden. People were weeding and chatting. It looked peaceful."),
    ("2025-07-15", "Tom sent an email at 9pm. I didn't reply until morning. Small boundary, but it felt important."),
    ("2025-07-16", "Rain all afternoon. Read on the couch. The sound on the roof was steady and kind."),
    ("2025-07-17", "Took the long way home from the store just to walk. The air smelled like cut grass and something blooming."),
    ("2025-07-18", "Thursday chess with Daniel. He beat me twice. I need to stop being predictable."),
    ("2025-07-19", "Raj and I grabbed lunch. He's thinking about switching teams. I told him I'd miss him but I get it."),
    ("2025-07-20", "Morning coffee. The porch has a good view of the old oak tree across the street. I'm going to like this."),
    ("2025-07-21", "Yuki and I signed up for the community garden plot. We're splitting it down the middle. She wants tomatoes, I want herbs."),
    ("2025-07-22", "Work dinner with the team. I almost didn't go but Raj convinced me. It was actually nice."),
    ("2025-07-23", "Couldn't sleep. Read until 2am. The book is about a woman who starts over in a new city. Not subtle, but comforting."),
    ("2025-07-24", "Evening walk. The sunsets in July are something else. Gold and pink everywhere."),
    ("2025-07-25", "First yoga class with Maria. She told me to stop clenching my jaw. I didn't realize I was doing it."),
    ("2025-07-26", "Saturday morning at the farmers market. Bought tomatoes, basil, and a weird squash. Yuki was there too."),
    ("2025-07-27", "Cooked for myself on a Wednesday. Usually I just toast something. Felt like I was taking care of myself properly."),
    ("2025-07-28", "Max texted about visiting next month. I said yes immediately. I miss that idiot."),
    ("2025-07-29", "Tom changed the project scope again. Third time this month. I'm learning to hold my plans loosely."),
    ("2025-07-30", "Evening walk. The neighborhood cats are out. One followed me for a block. I named her Maple."),
    ("2025-07-31", "End of the first month in the new place. I think this is going to be good. I think I'm going to be okay here."),

    # ================================================================
    # AUGUST 2025 — settling in, side project spark
    # ================================================================
    ("2025-08-01", "August. The garden plot needs weeding already. Yuki is very serious about her tomatoes."),
    ("2025-08-02", "Morning coffee on the porch. A butterfly landed on the railing. I watched it for five minutes."),
    ("2025-08-03", "Morning coffee ritual is becoming real. Same corner of the porch, same mug, same ten minutes before the world starts."),
    ("2025-08-04", "Walked to the library. Found a book on photography composition. Took it home without hesitation."),
    ("2025-08-05", "Started sketching ideas for the photography portfolio. Just notes on my phone so far, but it feels like something."),
    ("2025-08-06", "Yoga. Maria noticed I'm breathing deeper. I didn't notice until she said it."),
    ("2025-08-07", "Tom put me on a new project at work. It's fine. I just wish he'd asked instead of assigning."),
    ("2025-08-08", "Friday movie night. Watched a documentary about street photography. Got ideas for my own work."),
    ("2025-08-09", "Sarah and I went to the old bookstore on Third. I bought three books I don't need. She bought five."),
    ("2025-08-10", "Rain sounds all night. Left the window cracked. Woke up feeling rested for the first time in weeks."),
    ("2025-08-11", "Evening walk. The sunsets this month are ridiculous. Orange and purple like someone spilled paint."),
    ("2025-08-12", "Work was slow. Used the quiet time to organize my notes. Productive in a different way."),
    ("2025-08-13", "Mom called. She asked if I'm eating enough vegetables. I am. She worries anyway."),
    ("2025-08-14", "Yuki gave me a tomato from her garden. It was the best tomato I've ever had. She was smug about it."),
    ("2025-08-15", "Friday movie night. Watched an old Hitchcock film alone on the couch with dark chocolate. Perfect."),
    ("2025-08-16", "Saturday morning at the farmers market. Bought peaches and honey. Summer tastes good."),
    ("2025-08-17", "The community garden is producing. Got my first basil leaves. Tiny but they smell incredible."),
    ("2025-08-18", "Evening walk. The fireflies are out. I stopped and watched them blink in the dark."),
    ("2025-08-19", "Had a weirdly good day at work. Raj and I figured out a problem together and it just clicked."),
    ("2025-08-20", "Morning coffee. The basil from the garden in my coffee would be weird. But the smell is incredible."),
    ("2025-08-21", "Took photos around the neighborhood for the portfolio. The light on the old brick buildings was exactly right."),
    ("2025-08-22", "Thursday chess with Daniel. He's getting better at openings. So am I."),
    ("2025-08-23", "Grandma called. She told me about the roses she's growing. I love listening to her talk about flowers."),
    ("2025-08-24", "Sunday cooking. Made a big salad with garden herbs. Simple but satisfying."),
    ("2025-08-25", "Rain all day. I opened the window just to listen to it. I love rain sounds more than I should probably admit."),
    ("2025-08-26", "Work was intense. Tom is counting on me for the September deliverable. I'm counting on coffee."),
    ("2025-08-27", "Sunday cooking. Made Dad's chili recipe. It's not as good as his but it's getting closer."),
    ("2025-08-28", "Yoga. Maria taught a new pose. My balance is improving. Small things add up."),
    ("2025-08-29", "Jake texted. He's getting married next spring. I'm happy for him. I'm also a little jealous."),
    ("2025-08-30", "Walked to the park with my camera. The late summer light is golden and forgiving."),
    ("2025-08-31", "End of August. The apartment finally feels like mine. The books are on shelves, the plants are alive, the light is right."),

    # ================================================================
    # SEPTEMBER 2025 — work stress, missing old routines
    # ================================================================
    ("2025-09-01", "Labor Day. No labor. Read on the porch with coffee. Sarah dropped off scones."),
    ("2025-09-02", "Back to work after a long weekend. The inbox was brutal. Tom's already stressed."),
    ("2025-09-03", "Work is picking up. Tom is stressed and it's radiating through the whole team. I can feel my jaw clenching again."),
    ("2025-09-04", "Evening walk. The light is changing. September has a different quality than August."),
    ("2025-09-05", "Thursday chess with Daniel. He beat me three times. I need to stop opening with the same moves."),
    ("2025-09-06", "Saturday at the farmers market. The tomatoes are at their peak. Bought too many."),
    ("2025-09-07", "Yuki's tomato plants are enormous. Mine are... adequate. She gave me some of hers. I pretended to be offended."),
    ("2025-09-08", "Morning coffee. The air is cooler. September mornings have a bite that August didn't."),
    ("2025-09-09", "Late at the office. Skipped yoga. Maria texted to check in. I said I'd be back next week."),
    ("2025-09-10", "Rain. The kind that signals the end of summer. I sat by the window and listened."),
    ("2025-09-11", "Morning coffee on the porch was cold today. I forgot about it while reading. Still nice, just different."),
    ("2025-09-12", "Work dinner with the team. I almost said no but went anyway. It was fine. Raj made it bearable."),
    ("2025-09-13", "Dad's birthday. Called him. He said he's proud of the garden. He meant the community garden, not the apartment. That's Dad."),
    ("2025-09-14", "Sunday cooking. Made a big batch of soup. The kitchen is small but everything works."),
    ("2025-09-15", "The photography portfolio is growing. Twelve shots I'm actually proud of. Maybe fifteen if I'm generous."),
    ("2025-09-16", "Yoga. Maria focused on grounding. I felt rooted for the first time in weeks."),
    ("2025-09-17", "Work dinner with the team. I almost said no but went anyway. It was fine. Raj made it bearable."),
    ("2025-09-18", "Evening walk. The leaves are just starting to turn. September light is the best light."),
    ("2025-09-19", "Rain again. I sat by the open window for an hour just listening. This is the thing I'll miss most about this apartment."),
    ("2025-09-20", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2025-09-21", "Sunday cooking. Tried a new recipe from the cookbook Katie sent. It was complicated but the result was worth it."),
    ("2025-09-22", "Fall equinox. The seasons are turning. I can feel it in the air and in my bones."),
    ("2025-09-23", "Tom asked me to work Saturday. I said no. It was the hardest no I've said in a while."),
    ("2025-09-24", "Called Katie. She's doing well in Portland. We talked about photography. She has an eye I don't have."),
    ("2025-09-25", "Evening walk. The leaves are just starting to turn. September light is the best light."),
    ("2025-09-26", "Thursday chess. Daniel and I are evenly matched now. He's not happy about it. I am."),
    ("2025-09-27", "Volunteer tutoring session. The kid I'm paired with, Marcus, read a whole page without stopping today. That felt huge."),
    ("2025-09-28", "Rain sounds. I left the window cracked and fell asleep to the rhythm of it."),
    ("2025-09-29", "Max is coming next weekend. I need to clear the guest room. It's become a photography storage room."),
    ("2025-09-30", "End of September. The busy season at work is ahead. I'm bracing for it."),

    # ================================================================
    # OCTOBER 2025 — finding rhythm
    # ================================================================
    ("2025-10-01", "October. My favorite month. The air is cooler and everything feels more intentional."),
    ("2025-10-02", "Morning coffee. The porch is cold but the warmth of the mug compensates."),
    ("2025-10-03", "Max arrived. We hugged at the door. He brought hot sauce from the farmer's market near his place."),
    ("2025-10-04", "Showed Max the garden. He was impressed by Yuki's tomatoes and politely neutral about my herbs. Fair."),
    ("2025-10-05", "Cooked a big Sunday dinner with Max. He told me about his job, his roommate situation. I listened more than I talked."),
    ("2025-10-06", "Max left. The apartment feels quieter again. I forgot how much I like having someone around."),
    ("2025-10-07", "Back to work. The quiet after Max left makes the work feel louder."),
    ("2025-10-08", "Thursday chess with Daniel. I finally won one. He accused me of studying. I didn't, but I won't correct him."),
    ("2025-10-09", "Yoga. Maria said my posture is changing. I stand taller now. I didn't notice."),
    ("2025-10-10", "Morning coffee was perfect today. The temperature, the light, the silence. Some days everything just aligns."),
    ("2025-10-11", "Walked to the park with my camera. The autumn colors are starting. Red and gold everywhere."),
    ("2025-10-12", "Work deadline tomorrow. Stayed late but left at 7. Not 9. Progress."),
    ("2025-10-13", "Rain. I sat by the window and watched the leaves fall. There's something honest about autumn rain."),
    ("2025-10-14", "Yuki brought over soup from her garden tomatoes. We sat on the porch and talked about nothing important."),
    ("2025-10-15", "Evening walk. The streetlights are coming on earlier now. The neighborhood feels cozier in the dark."),
    ("2025-10-16", "The photography portfolio hit twenty shots. I'm starting to think about a website."),
    ("2025-10-17", "Thursday chess. Daniel brought a new opening. I lost, but I learned something."),
    ("2025-10-18", "Sarah and I went camping. First time in months. The fire, the stars, the quiet. I needed this more than I knew."),
    ("2025-10-19", "Camping day two. Made coffee on the old stove. Sarah laughed at how seriously I take the process."),
    ("2025-10-20", "Back from camping. Everything feels a little lighter. The apartment, the work, the head."),
    ("2025-10-21", "Morning coffee. The camping residue is still with me. I feel reset."),
    ("2025-10-22", "Work was productive. The break helped. I came back with fresh eyes."),
    ("2025-10-23", "Tom praised the project in front of the team. I said thank you and didn't downplay it. Growth."),
    ("2025-10-24", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2025-10-25", "Friday movie night. Rain sounds on the window. Dark chocolate. A film about a lighthouse keeper. Perfect."),
    ("2025-10-26", "Sunday cooking. Made a big pot of chili. The apartment smells like Dad's kitchen."),
    ("2025-10-27", "Marcus at the tutoring session read two pages today. I almost cried. I didn't. But close."),
    ("2025-10-28", "Yoga. Maria taught a breathing technique. I used it during a stressful work call. It worked."),
    ("2025-10-29", "Grandma sent a package. A scarf she knitted and a note that said 'Stay warm, stay kind.' I'm keeping the note."),
    ("2025-10-30", "Evening walk. The jack-o-lanterns are out. The neighborhood looks friendly and weird."),
    ("2025-10-31", "Halloween. Yuki and I handed out candy on the porch. One kid said my costume was 'vintage.' I was just wearing a sweater."),

    # ================================================================
    # NOVEMBER 2025 — family, holiday prep, gratitude
    # ================================================================
    ("2025-11-01", "November. The trees are almost bare. There's something honest about a tree with no leaves."),
    ("2025-11-02", "Morning coffee. The porch is cold now. I bundle up and drink faster."),
    ("2025-11-03", "Work is intense. Tom is counting on me for the November deliverable. I'm counting on coffee."),
    ("2025-11-04", "Evening walk. The bare trees let more light through. The neighborhood looks different without leaves."),
    ("2025-11-05", "Yoga with Maria. She focused on breathing today. I realized I hold my breath when I'm stressed."),
    ("2025-11-06", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2025-11-07", "Called Katie. She's doing well in Portland. We talked about photography. She has an eye I don't have."),
    ("2025-11-08", "Saturday at the farmers market. The last of the season. Bought root vegetables and apples."),
    ("2025-11-09", "Sunday cooking. Made a double batch of soup and froze half. Future me will be grateful."),
    ("2025-11-10", "Work was slow. Used the quiet time to organize my notes. Productive in a different way."),
    ("2025-11-11", "Veterans Day. Uncle Pete called. We talked for an hour. He's doing better since the surgery."),
    ("2025-11-12", "Evening walk. The cold air is sharp and good. I've been walking every day this month. It's become non-negotiable."),
    ("2025-11-13", "Raj and I finished the project ahead of schedule. Tom was genuinely surprised. We celebrated with gas station coffee."),
    ("2025-11-14", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2025-11-15", "Evening walk. The cold air is sharp and good. I've been walking every day this month. It's become non-negotiable."),
    ("2025-11-16", "Sunday cooking. Made a big pot of soup. The kitchen is small but everything works."),
    ("2025-11-17", "Mom texted about Thanksgiving plans. I said I'd bring the pie. She said bring two. She knows my pie is good."),
    ("2025-11-18", "Yoga. Maria said my shoulders are dropping. I carry less tension now."),
    ("2025-11-19", "The photography website is halfway done. Daniel helped me with the CSS. I'm terrible at CSS."),
    ("2025-11-20", "Evening walk. The neighborhood lights are starting to go up. Early decorations."),
    ("2025-11-21", "Morning coffee. The frost on the porch rail looked like lace. Took a photo. It might be my best one."),
    ("2025-11-22", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2025-11-23", "Planned the garden for next year with Yuki. We're adding sunflowers. She's very excited about sunflowers."),
    ("2025-11-24", "Work was steady. The November deliverable is done. I'm proud of how I handled the pressure."),
    ("2025-11-25", "Finished the November deliverable at work. Submitted it at 4pm on a Tuesday. I'm getting better at boundaries."),
    ("2025-11-26", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2025-11-27", "Thanksgiving at Mom and Dad's. The whole family. Max, Jake, Grandma. The pie was a hit. Both pies."),
    ("2025-11-28", "Black Friday. Didn't buy anything. Walked to the bookstore instead. Bought one book. That counts as restraint."),
    ("2025-11-29", "Evening walk. The neighborhood lights are up. Some houses go all out. Mine has one strand. That feels right."),
    ("2025-11-30", "End of November. I'm grateful for the quiet. For the garden. For Sarah and Max and Mom. For the morning coffee."),

    # ================================================================
    # DECEMBER 2025 — holidays, reflection, loneliness
    # ================================================================
    ("2025-12-01", "December. The apartment is cold in the mornings. I need to figure out the heating situation."),
    ("2025-12-02", "Morning coffee. The cold makes the mug feel warmer. Small comforts."),
    ("2025-12-03", "Put up a few lights. Nothing fancy. Just the window. It makes the whole room feel warmer."),
    ("2025-12-04", "Work was productive. The year is winding down but the deadlines aren't."),
    ("2025-12-05", "Sarah and I went to the holiday market. She bought ornaments. I bought dark chocolate and a candle."),
    ("2025-12-06", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2025-12-07", "Sunday cooking. Made gingerbread. The apartment smells like cloves and memory."),
    ("2025-12-08", "Yoga. Maria said my breathing is different now. Deeper. Slower. I feel it."),
    ("2025-12-09", "Work holiday party. I went for one hour. That was enough. Raj left at the same time.默契."),
    ("2025-12-10", "Evening walk. The neighborhood lights are up. Some houses go all out. Mine has one strand. That feels right."),
    ("2025-12-11", "Evening walk. The neighborhood lights are up. Some houses go all out. Mine has one strand. That feels right."),
    ("2025-12-12", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2025-12-13", "Called Mom. She's stressed about Christmas dinner. I told her I'd come early to help. She sounded relieved."),
    ("2025-12-14", "Sunday cooking. Made a big pot of soup. The kitchen is small but everything works."),
    ("2025-12-15", "Marcus read three pages at tutoring today. His mom sent a thank-you email. I read it three times."),
    ("2025-12-16", "Evening walk. The cold air is sharp and good. I've been walking every day this month. It's become non-negotiable."),
    ("2025-12-17", "Rain and cold. Sat by the window with coffee and listened. There's something about rain in December that feels honest."),
    ("2025-12-18", "Work was steady. The year is almost done. I'm ready for the break."),
    ("2025-12-19", "Finished the photography website. It's simple but it's mine. Sent the link to Katie. She said it was beautiful."),
    ("2025-12-20", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2025-12-21", "Winter solstice. The shortest day. I walked in the dark and watched the streetlights come on one by one."),
    ("2025-12-22", "Evening walk. The neighborhood lights are up. Some houses go all out. Mine has one strand. That feels right."),
    ("2025-12-23", "Drove to Mom and Dad's. The drive was quiet. I like the quiet drives. Just me and the road and the radio."),
    ("2025-12-24", "Christmas Eve. Mom's kitchen. The smell of cinnamon. Max telling bad jokes. This is what matters."),
    ("2025-12-25", "Christmas. Dad's chili. Mom's pie. Max's terrible jokes. Grandma's scarf around my neck. This is what matters."),
    ("2025-12-26", "The quiet after Christmas. Everyone's napping. I'm sitting in Dad's garden chair looking at the dormant beds."),
    ("2025-12-27", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2025-12-28", "Back home. The apartment is cold but familiar. Yuki left a note: 'Your basil is fine. I watered it.'"),
    ("2025-12-29", "Evening walk. The neighborhood lights are starting to come down. The holidays are fading."),
    ("2025-12-30", "End of the year. I'm tired but not the bad kind of tired. The kind that means you lived a full year."),
    ("2025-12-31", "New Year's Eve. Sarah came over. We watched the ball drop on my laptop because I don't have a TV. She said this is the year everything changes. I believe her."),

    # ================================================================
    # JANUARY 2026 — new year, fresh start, ambition
    # ================================================================
    ("2026-01-01", "New Year's Day. Coffee on the porch. Frost on everything. One resolution: be less afraid of good things."),
    ("2026-01-02", "Morning coffee. The new year feels different. Not better, just different. Fresh."),
    ("2026-01-03", "Back to work. Tom has a whole new plan for Q1. I'm cautiously optimistic."),
    ("2026-01-04", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2026-01-05", "Yoga with Maria. First class of the year. She said 'set an intention, not a resolution.' I liked that."),
    ("2026-01-06", "Evening walk. The neighborhood is quiet. Everyone is still in holiday mode."),
    ("2026-01-07", "Thursday chess with Daniel. He brought a new opening. I lost, but I learned something."),
    ("2026-01-08", "Work was productive. The new year energy is real."),
    ("2026-01-09", "Morning coffee. I've been journaling in my head for months. Maybe I should actually write things down."),
    ("2026-01-10", "Saturday at the farmers market. Winter market. Bought root vegetables and honey."),
    ("2026-01-11", "Sunday cooking. Made a new year soup. It's just regular soup but I called it new year soup."),
    ("2026-01-12", "Evening walk. The cold air is sharp and good. I've been walking every day this month. It's become non-negotiable."),
    ("2026-01-13", "Yuki and I planned the spring garden. She wants a pollinator section. I want more basil. We compromised."),
    ("2026-01-14", "Work was steady. The new plan is taking shape."),
    ("2026-01-15", "Work is steady. Not frantic, not boring. This might be the sweet spot."),
    ("2026-01-16", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2026-01-17", "Sarah and I had a long talk about what we want this year. She wants to travel. I want to build something."),
    ("2026-01-18", "Evening walk. The days are getting longer. You can feel it even though it's still dark at 5."),
    ("2026-01-19", "Evening walk. The days are getting longer. You can feel it even though it's still dark at 5."),
    ("2026-01-20", "Work was productive. The new year energy is real."),
    ("2026-01-21", "Marcus finished his first chapter book at tutoring. His teacher sent me a note. I'm keeping it next to Grandma's."),
    ("2026-01-22", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2026-01-23", "Photography portfolio update. Thirty shots now. Some of the garden ones are really good."),
    ("2026-01-24", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2026-01-25", "Rain sounds all night. Left the window cracked. Woke up feeling rested for the first time in weeks."),
    ("2026-01-26", "Evening walk. The neighborhood is quiet. Everyone is still in holiday mode."),
    ("2026-01-27", "Called Max. He's thinking about getting a dog. I told him to get a medium one. He's not ready for a big one."),
    ("2026-01-28", "Yoga. Maria said my shoulders are dropping. I carry less tension now."),
    ("2026-01-29", "Mom texted a photo of Dad's garden beds covered in snow. He's already planning what to plant in spring."),
    ("2026-01-30", "Evening walk. The cold air is sharp and good. I've been walking every day this month. It's become non-negotiable."),
    ("2026-01-31", "End of January. The year is new and full of possibility. I can feel it."),

    # ================================================================
    # FEBRUARY 2026 — winter blues, creative spark
    # ================================================================
    ("2026-02-01", "February. The longest month. Not because of the days — because of the waiting."),
    ("2026-02-02", "Morning coffee. The porch is cold but the warmth of the mug compensates."),
    ("2026-02-03", "Work was draining. Tom changed the plan again. Third time this quarter. I'm learning to hold my plans loosely."),
    ("2026-02-04", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2026-02-05", "Sarah came over with dark chocolate and a movie. We watched something forgettable and it was perfect."),
    ("2026-02-06", "Evening walk. The cold air is sharp and good. I've been walking every day this month. It's become non-negotiable."),
    ("2026-02-07", "Morning coffee. The porch was too cold so I sat inside by the window. Different spot, same ritual."),
    ("2026-02-08", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2026-02-09", "Yoga. Maria said 'you're holding less tension in your jaw.' I didn't even know she noticed."),
    ("2026-02-10", "Work was productive. The new year energy is real."),
    ("2026-02-11", "Thursday chess. Daniel and I are evenly matched now. He's not happy about it. I am."),
    ("2026-02-12", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2026-02-13", "Valentine's Day eve. Went to the bookstore alone. Bought a book about color theory for the photography work."),
    ("2026-02-14", "Valentine's Day. Sarah and I had dinner at the Thai place. Neither of us is seeing anyone. We're each other's valentine."),
    ("2026-02-15", "Evening walk. The neighborhood is quiet. Everyone is still in winter mode."),
    ("2026-02-16", "The garden is dormant but I went anyway. Yuki was there, pruning something. She says February pruning matters."),
    ("2026-02-17", "Work was steady. The new plan is taking shape."),
    ("2026-02-18", "Had an idea for a project. Something that helps people journal with memory. Like a private diary that remembers."),
    ("2026-02-19", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2026-02-20", "Can't stop thinking about the journal idea. Started sketching it on paper. Old school."),
    ("2026-02-21", "Evening walk. The cold air is sharp and good. I've been walking every day this month. It's become non-negotiable."),
    ("2026-02-22", "Sunday cooking. Made a big stew. Gave a portion to Yuki. She gave me tomatoes from her winter stash."),
    ("2026-02-23", "Work was productive. The new year energy is real."),
    ("2026-02-24", "Talked to Raj about the journal idea. He said it sounds like a hackathon project. He's right."),
    ("2026-02-25", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2026-02-26", "Rain. Sat by the window and sketched the app design. Three screens: write, remember, ask."),
    ("2026-02-27", "Evening walk. The days are getting longer. You can feel it even though it's still dark at 5."),
    ("2026-02-28", "End of February. The journal idea won't leave me alone. I think that means something."),

    # ================================================================
    # MARCH 2026 — spring energy, project momentum
    # ================================================================
    ("2026-03-01", "March. You can smell the thaw. The garden beds are waking up."),
    ("2026-03-02", "Morning coffee. The porch is usable again. First outdoor coffee since November. It tasted different. Better."),
    ("2026-03-03", "Started coding the journal app. Just the database and a basic entry form. But it felt real."),
    ("2026-03-04", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2026-03-05", "Yuki started her seedlings indoors. I started mine too. We're competing. Friendly competition."),
    ("2026-03-06", "Evening walk. The trees have buds. Tiny green promises everywhere."),
    ("2026-03-07", "Thursday chess. Daniel asked about the project. I explained it. He said 'that's actually cool.' That's high praise from Daniel."),
    ("2026-03-08", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2026-03-09", "Morning coffee. The porch is usable again. First outdoor coffee since November. It tasted different. Better."),
    ("2026-03-10", "Work was productive. The new year energy is real."),
    ("2026-03-11", "Work project is wrapping up. Tom seems satisfied. I'm satisfied with being satisfied."),
    ("2026-03-12", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2026-03-13", "The journal app has a reflection feature now. The AI reads your entry and gives a warm response. Tested it on my own entry."),
    ("2026-03-14", "Evening walk. The neighborhood is waking up. People are outside again."),
    ("2026-03-15", "Sunday cooking. Made Dad's chili recipe again. This time it was almost as good as his. Almost."),
    ("2026-03-16", "Work was steady. The new plan is taking shape."),
    ("2026-03-17", "Sarah asked about the project. I showed her the prototype. She said 'this feels personal.' That's the point."),
    ("2026-03-18", "Evening walk. The trees have buds. Tiny green promises everywhere."),
    ("2026-03-19", "Evening walk. The trees have buds. Tiny green promises everywhere."),
    ("2026-03-20", "Spring equinox. Planted the first herbs in the garden. Yuki's sunflower seeds are already sprouting."),
    ("2026-03-21", "Spring equinox. Planted the first herbs in the garden. Yuki's sunflower seeds are already sprouting."),
    ("2026-03-22", "Work was productive. The new year energy is real."),
    ("2026-03-23", "Marcus at tutoring read a whole chapter without stopping. His mom cried. I almost did too."),
    ("2026-03-24", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2026-03-25", "The journal app can remember things now. I wrote about coffee and it recalled a past entry about the porch. Magic."),
    ("2026-03-26", "Evening walk. The neighborhood is waking up. People are outside again."),
    ("2026-03-27", "Raj came over to test the app. He wrote about his cat. The reflection was warm and specific. He looked surprised."),
    ("2026-03-28", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2026-03-29", "Rain on the window. The app works. The herbs are growing. Sarah texted 'proud of you.' Good day."),
    ("2026-03-30", "Evening walk. The neighborhood is waking up. People are outside again."),
    ("2026-03-31", "End of March. Spring is here. The project is real. I feel like I'm building something that matters."),

    # ================================================================
    # APRIL 2026 — journaling becomes real
    # ================================================================
    ("2026-04-01", "April. The garden is exploding. Yuki's sunflowers are already a foot tall."),
    ("2026-04-02", "Morning coffee. The herbs are doing well. The mint is aggressive. I respect that."),
    ("2026-04-03", "Added the Remember panel to the app. It shows the people, projects, and themes it's noticed. It saw Sarah before I told it about Sarah."),
    ("2026-04-04", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2026-04-05", "Morning coffee on the porch. The herbs are doing well. The mint is aggressive. I respect that."),
    ("2026-04-06", "Evening walk. The neighborhood is blooming. Every yard has something different growing."),
    ("2026-04-07", "Called Mom. Told her about the project. She said 'so it's like a diary that talks back?' Close enough, Mom."),
    ("2026-04-08", "Work was productive. The new year energy is real."),
    ("2026-04-09", "Thursday chess. Daniel beat me. He said 'you're distracted by your project.' He's right and I'm not sorry."),
    ("2026-04-10", "Evening walk. The neighborhood is blooming. Every yard has something different growing."),
    ("2026-04-11", "Tested the app's memory with twenty entries. It recalled the camping trip when I wrote about fire. I got chills."),
    ("2026-04-12", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2026-04-13", "Sunday cooking. Made soup from the garden herbs. The basil was incredible. Yuki was right about basil."),
    ("2026-04-14", "Work was steady. The new plan is taking shape."),
    ("2026-04-15", "Tom noticed I seem happier. I didn't tell him why. Some things are just yours."),
    ("2026-04-16", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2026-04-17", "Yoga. Maria asked what changed. I said I started journaling. She said 'the writing shows in your body.'"),
    ("2026-04-18", "Evening walk. The neighborhood is blooming. Every yard has something different growing."),
    ("2026-04-19", "Evening walk. The neighborhood is blooming. Every yard has something different growing."),
    ("2026-04-20", "Work was productive. The new year energy is real."),
    ("2026-04-21", "Sarah tested the app. She wrote about her sister. The reflection was so specific she screenshot it."),
    ("2026-04-22", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2026-04-23", "Added source receipts to the app. When it recalls a past entry, it shows the exact date and snippet. Proof of memory."),
    ("2026-04-24", "Evening walk. The neighborhood is blooming. Every yard has something different growing."),
    ("2026-04-25", "Rain. Perfect rain day. Worked on the app all afternoon. The Remember panel now groups by type: people, projects, themes."),
    ("2026-04-26", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2026-04-27", "Marcus finished his reading level assessment. Two grade levels up from where he started. I brought cupcakes to tutoring."),
    ("2026-04-28", "Evening walk. The neighborhood is blooming. Every yard has something different growing."),
    ("2026-04-29", "Grandma called. I told her about the project. She said 'I wish I'd had something like that when I was your age.'"),
    ("2026-04-30", "End of April. The app is getting good. The garden is getting tall. I feel like I'm growing alongside both of them."),

    # ================================================================
    # MAY 2026 — patterns, refinement, community
    # ================================================================
    ("2026-05-01", "May. The sunflowers are taller than Yuki. She's very proud."),
    ("2026-05-02", "Morning coffee. The mint has taken over one corner of the garden. I let it. Mint should be free."),
    ("2026-05-03", "Morning coffee. The mint has taken over one corner of the garden. I let it. Mint should be free."),
    ("2026-05-04", "Morning coffee ritual is becoming real. Same mug, same spot, same ten minutes."),
    ("2026-05-05", "Work deadline moved up. But this time I planned for it. Buffer time is a gift to your future self."),
    ("2026-05-06", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2026-05-07", "Thursday chess. Daniel asked to see the app code. He found a bug. Fixed it in two minutes. Good friend."),
    ("2026-05-08", "Evening walk. The neighborhood is blooming. Every yard has something different growing."),
    ("2026-05-09", "Raj and I had coffee. He asked about the hackathon timeline. I said three weeks. He said 'you're going to win.'"),
    ("2026-05-10", "Sarah texted about brunch. I said yes before I could overthink it."),
    ("2026-05-11", "Yoga. Maria taught a new breathing technique. I used it during a stressful work call. It worked."),
    ("2026-05-12", "Work was productive. The new year energy is real."),
    ("2026-05-13", "Forgot my vitamins again. Third time this month. I keep meaning to make mornings simpler."),
    ("2026-05-14", "Rain. Cold rain. I stayed inside and read. The window was fogged up."),
    ("2026-05-15", "Added the 'This Week' feature to the app. It looks at your recent entries and notices patterns. It noticed I write about coffee a lot."),
    ("2026-05-16", "Side project demo broke in front of two people. Embarrassing but fixable."),
    ("2026-05-17", "Evening walk. The jasmine is blooming. The whole street smells sweet."),
    ("2026-05-18", "Work was steady. The new plan is taking shape."),
    ("2026-05-19", "Marcus read his first chapter book cover to cover. His mom sent me a photo of him holding it up. I'm framing that."),
    ("2026-05-20", "Evening walk. The neighborhood is blooming. Every yard has something different growing."),
    ("2026-05-21", "Katie called from Portland. She wants to do the photography portfolio justice. She's flying out next month to help."),
    ("2026-05-22", "Went for a walk after work instead of collapsing on the couch. Small win."),
    ("2026-05-23", "The app's demo mode works. Seeded it with sample entries. Even I got a little emotional reading the reflections."),
    ("2026-05-24", "Saturday. Cleaned the apartment. Put on music. Made it a thing instead of a chore."),
    ("2026-05-25", "Yuki and I harvested the first herbs. Made pesto. She brought tomatoes. We ate on her porch."),
    ("2026-05-26", "Rain. The kind that makes you want to stay inside and read. I did."),
    ("2026-05-27", "Work is steady. The hackathon prep is intense. I'm sleeping less but it's the good kind of tired."),
    ("2026-05-28", "Late night coding. The side project is almost ready to show people."),
    ("2026-05-29", "Friday movie night. Watched a documentary about memory. Felt very on-brand for my current life."),
    ("2026-05-30", "Evening walk. The neighborhood is blooming. Every yard has something different growing."),
    ("2026-05-31", "End of May. The hackathon is two weeks away. The app is almost ready. I'm almost ready."),

    # ================================================================
    # JUNE 2026 — hackathon push, submission, reflection
    # ================================================================
    ("2026-06-01", "June. The hackathon submission is this week. Time to polish everything."),
    ("2026-06-02", "Mom called. She asked if the project is done. I said almost. She said 'you always say almost.'"),
    ("2026-06-03", "Sarah tested the full flow: write, reflect, remember, recall. She said 'this is going to win.'"),
    ("2026-06-04", "Lost three hours on the side project tonight and didn't notice the time. First time in weeks I actually felt like myself."),
    ("2026-06-05", "Final polish on the app. Katie arrived to help review the photography portfolio. She has an incredible eye."),
    ("2026-06-06", "Hackathon submission day. Uploaded the app. My hands were shaking. Sarah was on speaker. Whatever happens, I made this. The journal remembers everything. I'm glad it does."),
]
