"""Pocket Confidant — a private, fully-local AI journaling companion.

A diary is the most private thing you own — you would never send it to a cloud
AI. So the only honest fit is a small model running 100% on-device: no cloud, no
account, no subscription, works in airplane mode. Each entry, the companion gives
a short warm reflection, asks exactly ONE good question, and — only when genuinely
relevant — calls back to something you wrote days ago, using private on-device
semantic memory.

Run it:
    source .venv/bin/activate
    python apps/confidant/app.py

DB defaults to ~/.pocket-confidant/journal.db; override with POCKET_CONFIDANT_DB.
"""
from __future__ import annotations

import html
import inspect
import os
import re
import sys
import time
from datetime import date
from pathlib import Path

# Make the repo root importable so `engine` resolves whether run from anywhere.
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

try:
    import gradio as gr
except Exception:  # pragma: no cover - lets helper-level tests import this module
    gr = None

from engine import confidant
from engine.store import Entry, JournalStore

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
DB_PATH = os.environ.get(
    "POCKET_CONFIDANT_DB", str(Path.home() / ".pocket-confidant" / "journal.db")
)


def _load_version_info() -> dict:
    """Read repo-root metadata.json (auto-generated by scripts/bump_version.py).

    Falls back gracefully to the raw VERSION file if metadata.json is missing
    or stale — the UI should never crash because of a missing version file.
    """
    meta_path = _REPO_ROOT / "metadata.json"
    if meta_path.exists():
        try:
            import json as _json
            return _json.loads(meta_path.read_text())
        except Exception:
            pass
    version_path = _REPO_ROOT / "VERSION"
    if version_path.exists():
        return {"version": version_path.read_text().strip(), "state": "unknown"}
    return {"version": "0.0.0", "state": "unknown"}


def _version_footer_html() -> str:
    info = _load_version_info()
    version = html.escape(str(info.get("version", "0.0.0")))
    state = str(info.get("state", "unknown"))
    branch = html.escape(str(info.get("branch", "")))
    commit = html.escape(str(info.get("commit", "")))

    state_label = {
        "prerelease": "pre-release",
        "released-clean": "released",
        "released-with-build": "released",
        "no-git": "no-git",
    }.get(state, state)

    bits = [f'<span class="pc-ver-version">v{version}</span>']
    if state_label:
        bits.append(f'<span class="pc-ver-state pc-ver-state--{state}">{state_label}</span>')
    if branch and commit:
        bits.append(f'<span class="pc-ver-git">{branch}@{commit}</span>')
    inner = '<span class="pc-ver-dot">·</span>'.join(bits)

    return (
        '<div id="pc-version-footer">'
        f'{inner}'
        '</div>'
    )


def _story_stats() -> dict:
    """Summarize the current journal so the landing UI feels alive."""
    try:
        stats = get_entry_stats()
    except Exception:
        stats = {"total_entries": 0, "avg_words": 0}
    try:
        streak = get_writing_streak()
    except Exception:
        streak = {"current": 0, "longest": 0}
    try:
        callbacks = sum(1 for e in STORE.recent(5) if (e.callback or "").strip())
    except Exception:
        callbacks = 0
    return {
        "total_entries": int(stats.get("total_entries", 0) or 0),
        "avg_words": int(stats.get("avg_words", 0) or 0),
        "streak_current": int(streak.get("current", 0) or 0),
        "streak_longest": int(streak.get("longest", 0) or 0),
        "callbacks_recent": callbacks,
    }


def _pill_html(label: str, value: str, tone: str = "") -> str:
    tone_class = f" pc-pill--{tone}" if tone else ""
    return (
        f'<div class="pc-pill{tone_class}">'
        f'<span class="pc-pill-label" style="color:#6b735c;">{_esc(label)}</span>'
        f'<span class="pc-pill-value" style="color:#241d16;font-weight:700;">{_esc(value)}</span>'
        '</div>'
    )


def _landing_html() -> str:
    """Landing copy that makes the product story obvious at a glance."""
    return (
        '<div class="pc-hero" style="background: linear-gradient(180deg, rgba(255,253,248,0.99), rgba(236,225,206,0.99)); color: #2f281f;">'
        '<div class="pc-hero-kicker" style="color: #7a866c;">Private reflection, not a chatbot</div>'
        '<h1 style="color: #2f281f; opacity: 1;">Write one entry. Get one reflection. See the pattern.</h1>'
        '<div class="pc-hero-line">A private daily journal that notices what keeps repeating.</div>'
        '<p class="pc-hero-copy" style="color: #473c2f;">'
        'Pocket Confidant is a private journal on your device. You write about your day, it gives back '
        'one reflection and one question, then it reaches for a past entry only when the match is real.'
        '</p>'
        '<div class="pc-pill-row">'
        f'{_pill_html("You write", "one real thing from today", "warm")}'
        f'{_pill_html("I reply", "one reflection, one question", "accent")}'
        f'{_pill_html("I remember", "only when a past entry truly fits", "sage")}'
        '</div>'
        '</div>'
    )


def _pulse_html(stats: dict, callback_ready: bool = False) -> str:
    """Small living visual hook inspired by the Petriarium work, but journal-first."""
    entries = int(stats.get("total_entries", 0) or 0)
    streak = int(stats.get("streak_current", 0) or 0)
    avg_words = int(stats.get("avg_words", 0) or 0)
    if callback_ready:
        tone = "awake"
        status = "A real callback just landed."
        badge = "memory linked"
    elif entries >= 8:
        tone = "growing"
        status = "It has enough history to notice patterns."
        badge = "memory growing"
    elif entries >= 1:
        tone = "listening"
        status = "Your journal is starting to feel known."
        badge = "listening"
    else:
        tone = "quiet"
        status = "Start with one line and let it learn."
        badge = "quiet"
    return (
        f'<div class="pc-pulse pc-pulse--{tone}" style="background: linear-gradient(180deg, rgba(255,253,248,0.99), rgba(236,225,206,0.99)); color: #2f281f;">'
        '<div class="pc-orb-shell">'
        '<div class="pc-orb"></div>'
        '<div class="pc-orb-ring"></div>'
        '<div class="pc-orb-leaf pc-orb-leaf--left"></div>'
        '<div class="pc-orb-leaf pc-orb-leaf--right"></div>'
        '</div>'
        '<div class="pc-pulse-copy">'
        '<div class="pc-pulse-label" style="color: #7a866c;">Companion state</div>'
        f'<div class="pc-pulse-status" style="color: #241d16;font-weight:500;">{_esc(status)}</div>'
        f'<div class="pc-pulse-badge" style="color: #7a866c; background: rgba(138,154,123,0.14);">{_esc(badge)}</div>'
        '<div class="pc-pulse-stats" style="color: #4b4033;">'
        f'{entries} entries · {streak}-day streak · {avg_words} avg words'
        '</div>'
        '</div>'
        '</div>'
    )


def _utility_strip_html() -> str:
    return (
        '<div class="pc-utility-strip">'
        '<span style="color: #4f4335;">Private by design</span>'
        '<span style="color: #4f4335;">Reflection every day</span>'
        '<span style="color: #4f4335;">One grounded question</span>'
        '<span style="color: #4f4335;">Memory only when it fits</span>'
        '</div>'
    )


def _how_it_works_html() -> str:
    return (
        '<div class="pc-explainer">'
        '<div class="pc-explainer-kicker">How it works</div>'
        '<div class="pc-explainer-grid">'
        '<div class="pc-step"><div class="pc-step-num">1</div><div><div class="pc-step-title">Write</div><div class="pc-step-copy">Type one real line about today.</div></div></div>'
        '<div class="pc-step"><div class="pc-step-num">2</div><div><div class="pc-step-title">Reflect</div><div class="pc-step-copy">You always get a short reflection and one grounded question.</div></div></div>'
        '<div class="pc-step"><div class="pc-step-num">3</div><div><div class="pc-step-title">Remember</div><div class="pc-step-copy">Only related past entries come back, so memory stays selective.</div></div></div>'
        '</div>'
        '<div class="pc-explainer-foot">Private on your device. No cloud. No account.</div>'
        '</div>'
    )


def _sample_prompts_html() -> str:
    return (
        '<div class="pc-samples">'
        '<div class="pc-samples-kicker">Try writing about</div>'
        '<div class="pc-samples-row">'
        '<span class="pc-sample">a moment that felt heavy</span>'
        '<span class="pc-sample">one thing you noticed today</span>'
        '<span class="pc-sample">what you want tomorrow to feel like</span>'
        '</div>'
        '</div>'
    )


def _receipt_html(entries: list[Entry], limit: int = 2) -> str:
    """Render a compact source-receipt block for recalled entries."""
    if not entries:
        return '<div class="pc-receipts"><div class="pc-receipts-head">source receipts</div><div class="pc-empty">No receipts yet.</div></div>'
    blocks = ['<div class="pc-receipts">', '<div class="pc-receipts-head">source receipts</div>']
    for e in entries[:limit]:
        snippet = (e.text or "").strip().replace("\n", " ")
        if len(snippet) > 220:
            snippet = snippet[:220] + "..."
        blocks.append(
            '<div class="pc-receipt">'
            f'<div class="pc-receipt-date">{_esc(e.when)}</div>'
            f'<div class="pc-receipt-text">{_esc(snippet)}</div>'
            '</div>'
        )
    blocks.append("</div>")
    return "\n".join(blocks)

# Only expose the single model we actually want to use.
MODELS = ["minicpm-v:latest"]
DEFAULT_MODEL = os.environ.get("POCKET_CONFIDANT_MODEL", "minicpm-v:latest")

_THEME_CSS = (Path(__file__).resolve().parent / "theme.css").read_text(encoding="utf-8")

# One shared, on-device store. SQLite is single-process here; Gradio's default
# queue serializes calls, which keeps the connection safe for this demo.
STORE = JournalStore(DB_PATH)


# --------------------------------------------------------------------------- #
# Rendering helpers (return HTML strings for the styled cards)
# --------------------------------------------------------------------------- #
def _esc(text: str) -> str:
    return html.escape((text or "").strip())


def _card_html(reflection: str, question: str, callback: str, model: str) -> str:
    """The companion's response, as a styled paper card."""
    parts = ['<div class="pc-card">']
    if callback and callback.strip():
        parts.append(f'<div class="pc-callback">{_esc(callback)}</div>')
    if reflection and reflection.strip():
        parts.append(f'<div class="pc-reflection">{_esc(reflection)}</div>')
    if question and question.strip():
        parts.append(f'<div class="pc-question">{_esc(question)}</div>')
    parts.append(
        f'<div class="pc-meta">reflected locally · {_esc(model)} · on-device</div>'
    )
    parts.append("</div>")
    return "\n".join(parts)


def _empty_state_html() -> str:
    return (
        '<div class="pc-empty">'
        "Nothing here yet — and that's the point: this page is just yours.<br>"
        "Write a line about your day above. The companion will read it on this "
        "machine, reflect a little, and ask one question. Over time it starts to "
        "remember — privately, with no cloud and no account."
        "</div>"
    )


def _timeline_html() -> str:
    """History of past entries, most-recent first, with the companion's echo."""
    entries = sorted(STORE.all(), key=lambda e: (e.ts, e.id), reverse=True)
    if not entries:
        return _empty_state_html()
    blocks = [
        '<div class="pc-timeline-shell">',
        '<div class="pc-timeline-top">',
        '<div class="pc-timeline-head">Your journal</div>',
        '<div class="pc-timeline-sub">Most recent entries first, with the companion\'s note beneath each one.</div>',
        '</div>',
    ]
    for e in reversed(entries):  # most recent first
        block = ['<div class="pc-entry-block">']
        block.append(f'<div class="pc-date">{_esc(e.when)}</div>')
        block.append(f'<div class="pc-text">{_esc(e.text)}</div>')
        if (e.reflection and e.reflection.strip()) or (e.question and e.question.strip()):
            echo = ['<div class="pc-echo">']
            if e.reflection and e.reflection.strip():
                echo.append(_esc(e.reflection))
            if e.question and e.question.strip():
                echo.append(f'<span class="pc-q"> {_esc(e.question)}</span>')
            echo.append("</div>")
            block.append("".join(echo))
        block.append("</div>")
        blocks.append("\n".join(block))
    blocks.append("</div>")
    return "\n".join(blocks)


def _recent_entries_html(limit: int = 3) -> str:
    """Compact preview of the newest entries so the journal is visible immediately."""
    entries = sorted(STORE.all(), key=lambda e: (e.ts, e.id), reverse=True)
    if not entries:
        return (
            '<div class="pc-recent-shell">'
            '<div class="pc-timeline-head">Recent entries</div>'
            '<div class="pc-empty">No entries yet. Write the first line to start the journal.</div>'
            '</div>'
        )
    recent = entries[:limit]
    blocks = [
        '<div class="pc-recent-shell">',
        '<div class="pc-timeline-head">Recent entries</div>',
    ]
    for e in recent:
        block = ['<div class="pc-recent-entry">']
        block.append(f'<div class="pc-date">{_esc(e.when)}</div>')
        snippet = (e.text or "").strip()
        if len(snippet) > 140:
            snippet = snippet[:140].rstrip() + "..."
        block.append(f'<div class="pc-text">{_esc(snippet)}</div>')
        if (e.reflection and e.reflection.strip()) or (e.question and e.question.strip()):
            echo = ['<div class="pc-echo">']
            if e.reflection and e.reflection.strip():
                echo.append(_esc(e.reflection))
            if e.question and e.question.strip():
                echo.append(f'<span class="pc-q"> {_esc(e.question)}</span>')
            echo.append("</div>")
            block.append("".join(echo))
        block.append("</div>")
        blocks.append("\n".join(block))
    blocks.append("</div>")
    return "\n".join(blocks)


def _recent_entries_html(limit: int = 3) -> str:
    """Compact preview of the newest entries so the journal is visible immediately."""
    entries = STORE.all()
    if not entries:
        return (
            '<div class="pc-recent-shell">'
            '<div class="pc-timeline-head">Recent entries</div>'
            '<div class="pc-empty">No entries yet. Write the first line to start the journal.</div>'
            '</div>'
        )
    recent = list(reversed(entries[-limit:]))
    blocks = [
        '<div class="pc-recent-shell">',
        '<div class="pc-timeline-head">Recent entries</div>',
    ]
    for e in recent:
        block = ['<div class="pc-recent-entry">']
        block.append(f'<div class="pc-date">{_esc(e.when)}</div>')
        snippet = (e.text or "").strip()
        if len(snippet) > 140:
            snippet = snippet[:140].rstrip() + "..."
        block.append(f'<div class="pc-text">{_esc(snippet)}</div>')
        if (e.reflection and e.reflection.strip()) or (e.question and e.question.strip()):
            echo = ['<div class="pc-echo">']
            if e.reflection and e.reflection.strip():
                echo.append(_esc(e.reflection))
            if e.question and e.question.strip():
                echo.append(f'<span class="pc-q"> {_esc(e.question)}</span>')
            echo.append("</div>")
            block.append("".join(echo))
        block.append("</div>")
        blocks.append("\n".join(block))
    blocks.append("</div>")
    return "\n".join(blocks)


def _strip_thinking(text: str) -> str:
    """Strip various thinking/reasoning tags from model output."""
    text = re.sub(r"<think>.*?</think>", "", text or "", flags=re.DOTALL)
    text = re.sub(r"<\|reasoning\|>.*?<\|/reasoning\|>", "", text, flags=re.DOTALL)
    text = re.sub(r"<\|begin_of_thought\|>.*?<\|end_of_thought\|>", "", text, flags=re.DOTALL)
    return text.strip()


def _format_chat(history: list[dict]) -> str:
    """Render chat history as styled HTML bubbles."""
    parts = ['<div class="chat-history">']
    for msg in history:
        role = msg.get("role", "")
        content = html.escape(msg.get("content", ""))
        if msg.get("loading"):
            parts.append(f'<div class="chat-thinking">{content}</div>')
        else:
            label = "You" if role == "user" else "Companion"
            parts.append(
                f'<div class="chat-msg chat-{role}">'
                f'<div><div class="chat-label">{label}</div>'
                f'<div class="chat-bubble">{content}</div></div>'
                f"</div>"
            )
    parts.append("</div>")
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# Actions
# --------------------------------------------------------------------------- #
def on_submit(entry_text: str, model: str):
    """Reflect on a new entry, persist it, refresh the timeline."""
    text = (entry_text or "").strip()
    current_stats = _story_stats()
    if not text:
        return (
            '<div class="pc-card"><div class="pc-reflection">'
            "Whenever you're ready — even one sentence is enough."
            "</div></div>",
            _timeline_html(),
            entry_text,
            "",  # no submitted entry to display
            _pulse_html(current_stats, callback_ready=False),
        )

    model = model or DEFAULT_MODEL
    today = date.today().isoformat()
    ts = time.time()

    try:
        # before_id=None: recall can see all prior entries (this one isn't stored yet).
        refl = confidant.reflect(text, store=STORE, model=model)
        reflection, question, callback = refl.reflection, refl.question, refl.callback
        used_model = refl.model or model
    except Exception as exc:  # local model offline / pulled mid-demo, etc.
        reflection = (
            "I couldn't reach the local model just now, so I've still saved what "
            "you wrote — it stays right here on your machine."
        )
        question = "Want to try the reflection again in a moment?"
        callback = ""
        used_model = model
        reflection += f"  ({type(exc).__name__})"

    # Persist (computes a private on-device embedding for future recall).
    try:
        STORE.add(text, day=today, ts=ts, reflection=reflection, question=question)
    except Exception:
        pass  # never lose the user's words to a storage hiccup in a demo

    card = _card_html(reflection, question, callback, used_model)
    # Show the submitted entry above the reflection card
    submitted_html = (
        '<div class="pc-submitted-entry">'
        '<div class="pc-submitted-label">Your entry</div>'
        f'<div class="pc-submitted-text">{_esc(text)}</div>'
        f'<div class="pc-submitted-date">{_esc(today)}</div>'
        "</div>"
    )
    # Don't clear the textarea — keep it visible for reference
    return card, _timeline_html(), entry_text, submitted_html, _pulse_html(_story_stats(), callback_ready=bool(callback.strip()))


def on_week(model: str):
    """Gentle 2-3 sentence reflection on recurring threads across recent entries."""
    entries = STORE.recent(7)
    if len(entries) < 2:
        return (
            '<div class="pc-week"><div class="pc-week-head">This week</div>'
            "Once you have a few entries, this will gently notice the threads "
            "running through your week — quietly, on this device."
            "</div>"
        )

    model = model or DEFAULT_MODEL
    joined = "\n".join(f"- ({e.when}) {e.text.strip()}" for e in entries)
    system = (
        confidant.PERSONA
        + "\n\nNow you are looking back over the last several journal entries at once."
    )
    user = (
        "Here are your most recent journal entries, oldest first:\n"
        f"{joined}\n\n"
        "In 2-3 plain, warm sentences, gently reflect on any recurring threads, "
        "tensions, or small shifts you notice across these days. Use your own "
        "specifics. Do not diagnose, do not give advice, do not list. If there's "
        "no real pattern, say so honestly and briefly. Return plain prose only — "
        "no JSON, no headers."
    )
    try:
        raw = confidant._chat(system, user, model=model)
        note = confidant._strip_thinking(raw).strip()
    except Exception as exc:
        note = (
            "Couldn't reach the local model just now — but your entries are all "
            f"still here on this machine. ({type(exc).__name__})"
        )

    return (
        '<div class="pc-week"><div class="pc-week-head">This week — '
        f"{_esc(model)}, on-device</div>"
        f"{_esc(note)}"
        "</div>"
    )


# --------------------------------------------------------------------------- #
# Analytics helpers
# --------------------------------------------------------------------------- #
def get_entry_stats():
    from engine.analytics import get_entry_stats as _get
    return _get(DB_PATH)


def get_writing_streak():
    from engine.analytics import get_writing_streak as _get
    return _get(DB_PATH)


# --------------------------------------------------------------------------- #
# UI
# --------------------------------------------------------------------------- #
def build() -> gr.Blocks:
    if gr is None:
        raise RuntimeError(
            "gradio is not installed in this environment. "
            "Run: uv pip install -r apps/confidant/requirements.txt"
        )
    # Gradio 4/5 took `css`/`theme` on the Blocks constructor; Gradio 6 moved them
    # to launch(). Detect which this version supports so the Off-Brand theme renders
    # either way (and we avoid a deprecation warning / silently-dropped css).
    _ctor_params = inspect.signature(gr.Blocks.__init__).parameters
    _accepts_ctor_css = "css" in _ctor_params and "theme" in _ctor_params

    _blocks_kwargs = dict(title="Pocket Confidant", analytics_enabled=False)
    if _accepts_ctor_css:
        _blocks_kwargs.update(css=_THEME_CSS, theme=gr.themes.Base())

    with gr.Blocks(**_blocks_kwargs) as demo:
        # Theme toggle button (sun/moon)
        _theme_toggle_js = """
        () => {
          const root = document.documentElement;
          const body = document.body;
          const host = document.querySelector(".gradio-container");
          const isDark = !(root.classList.contains("dark") || body.classList.contains("dark"));
          root.classList.toggle("dark", isDark);
          body.classList.toggle("dark", isDark);
          if (host) host.classList.toggle("dark", isDark);
          root.setAttribute("data-pc-theme", isDark ? "dark" : "light");
          body.setAttribute("data-pc-theme", isDark ? "dark" : "light");
          if (host) host.setAttribute("data-pc-theme", isDark ? "dark" : "light");
          let btn = document.querySelector("#pc-theme-toggle button");
          if (!btn) btn = document.getElementById("pc-theme-toggle");
          if (btn) btn.textContent = isDark ? "🌙" : "☀️";
          localStorage.setItem("pc-theme", isDark ? "dark" : "light");
        }
        """
        theme_toggle = gr.Button("🌙", elem_id="pc-theme-toggle", variant="secondary")
        theme_toggle.click(
            fn=lambda: None,
            inputs=[],
            outputs=[],
            js=_theme_toggle_js,
        )
        gr.HTML(
            '<script>'
            'window.addEventListener("load", function() {'
            '  const useDark = true;'
            '  const btn = document.querySelector("#pc-theme-toggle button") || document.getElementById("pc-theme-toggle");'
            '  if (useDark) {'
            '    document.documentElement.classList.add("dark");'
            '    document.body.classList.add("dark");'
            '    const host = document.querySelector(".gradio-container");'
            '    if (host) host.classList.add("dark");'
            '    document.documentElement.setAttribute("data-pc-theme", "dark");'
            '    document.body.setAttribute("data-pc-theme", "dark");'
            '    if (host) host.setAttribute("data-pc-theme", "dark");'
            '    if (btn) btn.textContent = "🌙";'
            '  }'
            '});'
            '</script>'
        )

        gr.HTML(
            '<div id="pc-masthead">'
            '<p class="pc-title">Pocket Confidant</p>'
            '<p class="pc-sub">a private journal that reflects back</p>'
            "</div>"
            '<div id="pc-privacy">'
            "100% on your device"
            '<span class="pc-dot">·</span>no cloud, no account'
            '<span class="pc-dot">·</span>works in airplane mode'
            "</div>"
        )

        gr.HTML(
            '<div class="pc-landing-row">'
            f'{_landing_html()}'
            f'{_pulse_html(_story_stats())}'
            '</div>'
        )
        gr.HTML(_how_it_works_html())
        gr.HTML(_sample_prompts_html())

        with gr.Tabs():
            with gr.Tab("Journal"):
                gr.HTML(_recent_entries_html())
                gr.HTML(_utility_strip_html())
                entry = gr.Textbox(
                    elem_id="pc-entry",
                    label="Today",
                    placeholder="Write one real thing from today. Even a single sentence is enough…",
                    lines=6,
                    show_label=False,
                )

                with gr.Row():
                    submit = gr.Button("Reflect", elem_id="pc-submit", elem_classes=["pc-primary"])
                    week = gr.Button("This week", elem_classes=["pc-quiet"])
                    model = gr.Dropdown(
                        choices=MODELS,
                        value=DEFAULT_MODEL,
                        label="model",
                        elem_id="pc-model",
                        interactive=True,
                    )

                response = gr.HTML(value="")
                submitted_entry = gr.HTML(value="")
                companion_pulse = gr.HTML(value=_pulse_html(_story_stats()))
                week_panel = gr.HTML(value="")
                timeline = gr.HTML(value=_timeline_html())

                submit.click(
                    on_submit,
                    inputs=[entry, model],
                    outputs=[response, timeline, entry, submitted_entry, companion_pulse],
                )
                entry.submit(
                    on_submit,
                    inputs=[entry, model],
                    outputs=[response, timeline, entry, submitted_entry, companion_pulse],
                )
                week.click(on_week, inputs=[model], outputs=[week_panel])

        with gr.Accordion("Journal details", open=False):
            gr.Markdown("### Stats and history")
            stats = get_entry_stats()
            streak = get_writing_streak()
            gr.Markdown(
                f'**{stats["total_entries"]}** entries | **{stats["avg_words"]}** avg words'
                f' | **{streak["current"]}** day streak | **{streak["longest"]}** longest streak'
            )
            gr.Markdown("*Charts coming soon!*")

        with gr.Accordion("\U0001f527 Developer Tools", open=False):
            gr.Markdown("**Warning:** These actions are destructive and cannot be undone.")
            with gr.Row():
                clear_btn = gr.Button("\U0001f5d1 Clear All Data", variant="stop")
                reload_btn = gr.Button("\U0001f504 Reload Demo Data")
            dev_status = gr.Markdown("")

            def on_clear_data():
                from engine.store import clear_all_entries
                count = clear_all_entries(DB_PATH)
                return (
                    f"Deleted {count} entries. The page has been reset.",
                    _timeline_html(),
                    "",
                    "",
                    "",
                    _pulse_html(_story_stats()),
                    "",
                )

            def on_reload_demo():
                from engine.store import seed_demo_data, clear_all_entries
                clear_all_entries(DB_PATH)
                count = seed_demo_data(DB_PATH)
                return (
                    f"Cleared and reloaded {count} demo entries.",
                    _timeline_html(),
                    "",
                    "",
                    "",
                    _pulse_html(_story_stats()),
                    "",
                )

            clear_btn.click(
                on_clear_data,
                outputs=[dev_status, timeline, response, submitted_entry, week_panel, companion_pulse, entry],
            )
            reload_btn.click(
                on_reload_demo,
                outputs=[dev_status, timeline, response, submitted_entry, week_panel, companion_pulse, entry],
            )

        gr.HTML(_version_footer_html())
        gr.HTML(
            '<div class="pc-footer">'
            '<a href="https://github.com/KeyArgo/pocket-confidant" target="_blank">'
            '📦 View on GitHub: KeyArgo/pocket-confidant'
            '</a>'
            '</div>'
        )

    # Remember whether the theme/css still need to be supplied at launch() time.
    demo._pc_needs_launch_css = not _accepts_ctor_css

    return demo


def main() -> None:
    if gr is None:
        raise RuntimeError(
            "gradio is not installed in this environment. "
            "Run: uv pip install -r apps/confidant/requirements.txt"
        )
    demo = build()
    launch_kwargs = dict(server_name="0.0.0.0")
    if getattr(demo, "_pc_needs_launch_css", False):
        # Gradio 6 path: theme + css belong on launch().
        launch_kwargs.update(css=_THEME_CSS, theme=gr.themes.Base())
    demo.launch(**launch_kwargs)


if __name__ == "__main__":
    main()
